/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelCashShiftsRouteImport } from './routes/panel.cash-shifts'
import { Route as PanelDashboardRouteImport } from './routes/panel.dashboard'
import { Route as PanelInventoryRouteImport } from './routes/panel.inventory'
import { Route as PanelSettingsRouteImport } from './routes/panel.settings'
import { Route as PanelTransactionsRouteImport } from './routes/panel.transactions'
import { Route as PanelDishesIndexRouteImport } from './routes/panel.dishes.index'
import { Route as PanelIngredientsIndexRouteImport } from './routes/panel.ingredients.index'
import { Route as PanelMenuIndexRouteImport } from './routes/panel.menu.index'
import { Route as PanelOrdersIndexRouteImport } from './routes/panel.orders.index'
import { Route as PanelOrdersOrderIdRouteImport } from './routes/panel.orders.$orderId'
import { Route as PanelProductsIndexRouteImport } from './routes/panel.products.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCashShiftsRoute = PanelCashShiftsRouteImport.update({
  id: '/cash-shifts',
  path: '/cash-shifts',
  getParentRoute: () => PanelRoute,
} as any)
const PanelDashboardRoute = PanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PanelRoute,
} as any)
const PanelInventoryRoute = PanelInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSettingsRoute = PanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PanelRoute,
} as any)
const PanelTransactionsRoute = PanelTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PanelRoute,
} as any)
const PanelDishesIndexRoute = PanelDishesIndexRouteImport.update({
  id: '/dishes/',
  path: '/dishes/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelIngredientsIndexRoute = PanelIngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelMenuIndexRoute = PanelMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelOrdersIndexRoute = PanelOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelOrdersOrderIdRoute = PanelOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProductsIndexRoute = PanelProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/cash-shifts': typeof PanelCashShiftsRoute
  '/panel/dashboard': typeof PanelDashboardRoute
  '/panel/inventory': typeof PanelInventoryRoute
  '/panel/settings': typeof PanelSettingsRoute
  '/panel/transactions': typeof PanelTransactionsRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/orders/$orderId': typeof PanelOrdersOrderIdRoute
  '/panel/dishes/': typeof PanelDishesIndexRoute
  '/panel/ingredients/': typeof PanelIngredientsIndexRoute
  '/panel/menu/': typeof PanelMenuIndexRoute
  '/panel/orders/': typeof PanelOrdersIndexRoute
  '/panel/products/': typeof PanelProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel/cash-shifts': typeof PanelCashShiftsRoute
  '/panel/dashboard': typeof PanelDashboardRoute
  '/panel/inventory': typeof PanelInventoryRoute
  '/panel/settings': typeof PanelSettingsRoute
  '/panel/transactions': typeof PanelTransactionsRoute
  '/panel': typeof PanelIndexRoute
  '/panel/orders/$orderId': typeof PanelOrdersOrderIdRoute
  '/panel/dishes': typeof PanelDishesIndexRoute
  '/panel/ingredients': typeof PanelIngredientsIndexRoute
  '/panel/menu': typeof PanelMenuIndexRoute
  '/panel/orders': typeof PanelOrdersIndexRoute
  '/panel/products': typeof PanelProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/cash-shifts': typeof PanelCashShiftsRoute
  '/panel/dashboard': typeof PanelDashboardRoute
  '/panel/inventory': typeof PanelInventoryRoute
  '/panel/settings': typeof PanelSettingsRoute
  '/panel/transactions': typeof PanelTransactionsRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/orders/$orderId': typeof PanelOrdersOrderIdRoute
  '/panel/dishes/': typeof PanelDishesIndexRoute
  '/panel/ingredients/': typeof PanelIngredientsIndexRoute
  '/panel/menu/': typeof PanelMenuIndexRoute
  '/panel/orders/': typeof PanelOrdersIndexRoute
  '/panel/products/': typeof PanelProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/panel'
    | '/panel/cash-shifts'
    | '/panel/dashboard'
    | '/panel/inventory'
    | '/panel/settings'
    | '/panel/transactions'
    | '/panel/'
    | '/panel/orders/$orderId'
    | '/panel/dishes/'
    | '/panel/ingredients/'
    | '/panel/menu/'
    | '/panel/orders/'
    | '/panel/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/panel/cash-shifts'
    | '/panel/dashboard'
    | '/panel/inventory'
    | '/panel/settings'
    | '/panel/transactions'
    | '/panel'
    | '/panel/orders/$orderId'
    | '/panel/dishes'
    | '/panel/ingredients'
    | '/panel/menu'
    | '/panel/orders'
    | '/panel/products'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/panel'
    | '/panel/cash-shifts'
    | '/panel/dashboard'
    | '/panel/inventory'
    | '/panel/settings'
    | '/panel/transactions'
    | '/panel/'
    | '/panel/orders/$orderId'
    | '/panel/dishes/'
    | '/panel/ingredients/'
    | '/panel/menu/'
    | '/panel/orders/'
    | '/panel/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PanelRoute: typeof PanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/cash-shifts': {
      id: '/panel/cash-shifts'
      path: '/cash-shifts'
      fullPath: '/panel/cash-shifts'
      preLoaderRoute: typeof PanelCashShiftsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/dashboard': {
      id: '/panel/dashboard'
      path: '/dashboard'
      fullPath: '/panel/dashboard'
      preLoaderRoute: typeof PanelDashboardRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/inventory': {
      id: '/panel/inventory'
      path: '/inventory'
      fullPath: '/panel/inventory'
      preLoaderRoute: typeof PanelInventoryRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/settings': {
      id: '/panel/settings'
      path: '/settings'
      fullPath: '/panel/settings'
      preLoaderRoute: typeof PanelSettingsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/transactions': {
      id: '/panel/transactions'
      path: '/transactions'
      fullPath: '/panel/transactions'
      preLoaderRoute: typeof PanelTransactionsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/dishes/': {
      id: '/panel/dishes/'
      path: '/dishes'
      fullPath: '/panel/dishes/'
      preLoaderRoute: typeof PanelDishesIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/ingredients/': {
      id: '/panel/ingredients/'
      path: '/ingredients'
      fullPath: '/panel/ingredients/'
      preLoaderRoute: typeof PanelIngredientsIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/menu/': {
      id: '/panel/menu/'
      path: '/menu'
      fullPath: '/panel/menu/'
      preLoaderRoute: typeof PanelMenuIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/orders/': {
      id: '/panel/orders/'
      path: '/orders'
      fullPath: '/panel/orders/'
      preLoaderRoute: typeof PanelOrdersIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/orders/$orderId': {
      id: '/panel/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/panel/orders/$orderId'
      preLoaderRoute: typeof PanelOrdersOrderIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/products/': {
      id: '/panel/products/'
      path: '/products'
      fullPath: '/panel/products/'
      preLoaderRoute: typeof PanelProductsIndexRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelCashShiftsRoute: typeof PanelCashShiftsRoute
  PanelDashboardRoute: typeof PanelDashboardRoute
  PanelInventoryRoute: typeof PanelInventoryRoute
  PanelSettingsRoute: typeof PanelSettingsRoute
  PanelTransactionsRoute: typeof PanelTransactionsRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelOrdersOrderIdRoute: typeof PanelOrdersOrderIdRoute
  PanelDishesIndexRoute: typeof PanelDishesIndexRoute
  PanelIngredientsIndexRoute: typeof PanelIngredientsIndexRoute
  PanelMenuIndexRoute: typeof PanelMenuIndexRoute
  PanelOrdersIndexRoute: typeof PanelOrdersIndexRoute
  PanelProductsIndexRoute: typeof PanelProductsIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelCashShiftsRoute: PanelCashShiftsRoute,
  PanelDashboardRoute: PanelDashboardRoute,
  PanelInventoryRoute: PanelInventoryRoute,
  PanelSettingsRoute: PanelSettingsRoute,
  PanelTransactionsRoute: PanelTransactionsRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelOrdersOrderIdRoute: PanelOrdersOrderIdRoute,
  PanelDishesIndexRoute: PanelDishesIndexRoute,
  PanelIngredientsIndexRoute: PanelIngredientsIndexRoute,
  PanelMenuIndexRoute: PanelMenuIndexRoute,
  PanelOrdersIndexRoute: PanelOrdersIndexRoute,
  PanelProductsIndexRoute: PanelProductsIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PanelRoute: PanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
